### ISSUE TITLE
get_roi_centroids could return a numpy array

### ISSUE THREAD

**Issue by fcollman** [AllenInstitute/swdb_2017_tools#18]
get_roi_centroids would be more useful if it returned a numpy array rather than a list.  Also, a minor point, the documentation should be precise about the python type it returns.. right now it returns a 'list', and I'd suggest it return a 'numpy.array' instead.  Could also tell you what size it should expect... 2xN or Nx2 ? (probably Nx2 but it's nice to be explicit).

**Comment by elijahc** [comment]
Pull request #21 implements this enhancement

**Comment by neuromusic** [comment]
or a pandas dataframe with columns x & y

**Comment by fcollman** [comment]
oh sorry! just accepted the PR.  Should probably settle on this sooner rather than later though as interface things are important to get straight

**Comment by elijahc** [comment]
are there other functions in the allensdk that return pandas dataframes?
from what I've seen so far (albeit not that much) the convention seems to be return numpy arrays and then convert them into pandas dataframes

If there's a precedent for returning dataframes I think that's fine, just want it to be consistent.

Maybe @dyf knows the answer to this?

**Comment by dyf** [comment]
I think students should do what works for them here.  

Returning DataFrames from allensdk functions is done sparingly in the SDK because previous SWDB cohorts struggled with them.  There was a "optional argument to return a DataFrame" pattern that was ugly that we don't do any more.  Currently most cache classes return metadata as lists of dictionaries, which you can import into pandas with a one-liner.

Maybe someone on twitter can poll whether the pandas tides have turned.

**Comment by dyf** [comment]
Personally, I like the numpy array option here.

**Comment by neuromusic** [comment]
"I think students should do what works for them here." :100:  

numpy is probably a more general solution.

in my own code, I would quickly convert this to a pandas dataframe because I could later `pd.merge` on it to annotate extracted features from my traces with x,y corrdinates.

**Comment by mabuice** [comment]
numpy++

(Did I just invent the future of scientific python?)

**Comment by fcollman** [comment]
seems the student who wrote this an at least a small majority are in favor of numpy for now, and so this issue is closed, but everyone should feel free to revisit if they feel that pandas is more useful to them in the future and change it, or make another function that uses this one to get a dataframe instead.
